// Ask for the user name... 
var name = prompt('What Is Your Name?')

document.getElementById("name").innerHTML = name
// Write into html div the current date and time... 
document.getElementById("time").innerHTML = Date()